### ISSUE TITLE
Swap for RocksDB

### ISSUE THREAD

**Issue by MarcusSorealheis** [buffdb/buffdb#8]

**Comment by jhpratt** [comment]
I have this partially implemented locally (and will push soon), but this shouldn't be released until https://github.com/rust-rocksdb/rust-rocksdb/pull/868 is available on crates.io.

**Comment by jhpratt** [comment]
There's still a bit to be gained in terms of error handling, as transactions cannot currently be used due to the linked issue. For that reason it's theoretically possible for what would otherwise be a transaction to succeed in changing the data but fail in changing the metadata of a blob object before an error is returned, leaving the _new_ data in place incorrectly.

With that said, the backend has been swapped for RocksDB throughout.
